name: Merge Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (Linting Check)
        run: npm run lint

      - name: Run TypeScript Type Check
        run: npm run type-check

      - name: Run Unit Tests
        run: npm test

      - name: Build Project (Vite)
        run: npm run build
